name: Build and Test WasmEdge WASI-NN examples

on:
  push:
    paths:
      - ".github/workflows/build_openvino.yml"
      - "openvino-mobilenet-raw/**"
      - "openvino-mobilenet-image/**"
      - "openvino-road-segmentation-adas/**"
  pull_request:
    branches: [master]
    paths-ignore:
      - "**/*.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  build_openvino_examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.71]
    container:
      image: wasmedge/wasmedge:latest
    steps:
      - name: Checkout Wasi-NN examples
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Rust-stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          target: wasm32-wasi

      - name: Install OpenVINO
        env:
          OPENVINO_VERSION: "2021.4.582"
          OPENVINO_YEAR: "2021"
        run: |
          ./scripts/install_openvino.sh

      - name: Install WasmEdge with Wasi-NN OpenVINO plugin
        env:
          CMAKE_BUILD_TYPE: "Release"
          VERSION: "0.13.1"
        run: |
          bash /opt/intel/openvino_2021/bin/setupvars.sh
          ldconfig
          curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v $VERSION -p /usr/local --plugins wasi_nn-openvino
          ldconfig
          ls -al /usr/local/lib

      - name: Build and run Rust example - openvino-mobilenet-raw
        working-directory: openvino-mobilenet-raw
        run: |
          bash /opt/intel/openvino_2021/bin/setupvars.sh
          ldconfig
          # cd rust
          # cargo build --target wasm32-wasi --release
          # cd ..
          bash download_mobilenet.sh
          wasmedge --dir .:. wasmedge-wasinn-example-mobilenet.wasm mobilenet.xml mobilenet.bin tensor-1x224x224x3-f32.bgr
      
      - name: Build and run Rust example - Mobilenet Image
        run: |
          bash -c "\
          source /opt/intel/openvino_2021/bin/setupvars.sh;\
          ldconfig;\
          cd WasmEdge && cmake --install build && cd ..;\
          cd openvino-mobilenet-image;\
          ./download_mobilenet.sh;\
          wasmedge --dir .:. wasmedge-wasinn-example-mobilenet-image.wasm mobilenet.xml mobilenet.bin input.jpg"
